Project Name:
- snake-game-made-in-java
Language:
- JDK v13 or above
- Apache Maven
Description:
- It is an awesome snake game with basic features
Features:
- Has the basic snake game
- Good graphics
- Made in java
- Uses no 3rd party sourced plugins / modules
- Uses default libraries
Owners:
- StarTwi
Contributors:
- NightZan999
